### ISSUE TITLE
Default value "*" is invalid for property [...] of resource cron_d. In Chef 13 this will become an error:

### ISSUE THREAD

**Issue by signe** [chef-cookbooks/cron#80]
### Cookbook version

1.7.6
### Chef-client version

12.10.24
### Platform Details

Ubuntu 16.04
### Scenario:

[What you are trying to achieve and you can't?]
### Steps to Reproduce:

```
file '/var/run/chef.running' do
    action      :touch
    user        'root'
    group       'root'
    mode        '0644'
end
```
### Expected Result:

No deprecation warnings
### Actual Result:

```
  Default value "*" is invalid for property minute of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x000000023cbbd8>. at 1 location:
    - /var/chef/cache/cookbooks/cron/resources/d.rb:26:in `class_from_file'
  Default value "*" is invalid for property hour of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x000000023cbbd8>. at 1 location:
    - /var/chef/cache/cookbooks/cron/resources/d.rb:27:in `class_from_file'
  Default value "*" is invalid for property day of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x000000023cbbd8>. at 1 location:
    - /var/chef/cache/cookbooks/cron/resources/d.rb:28:in `class_from_file'
  Default value "*" is invalid for property month of resource cron_d. In Chef 13 this will become an error: undefined method `validate_month' for #<Class:0x000000023cbbd8>. at 1 location:
    - /var/chef/cache/cookbooks/cron/resources/d.rb:29:in `class_from_file'
  Default value "*" is invalid for property weekday of resource cron_d. In Chef 13 this will become an error: undefined method `validate_dow' for #<Class:0x000000023cbbd8>. at 1 location:
    - /var/chef/cache/cookbooks/cron/resources/d.rb:30:in `class_from_file'
```

**Comment by bushong1** [comment]
This is still an issue.

**Comment by esabelhaus** [comment]
@tas50 I am going to dig into this, but do you have any suggestion as to how this might be solved before digging?

**Comment by tas50** [comment]
We're reworking this cookbook for Chef 13 and this should come along for the ride.
