### ISSUE TITLE
 No resource or method named `create_template'

### ISSUE THREAD

**Issue by cthomaspdx** [chef-cookbooks/cron#91]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
Using cron (4.0.0)
### Chef-client version
[Version of chef-client in your environment]
Using chef-client (5.0.0)

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
Debian Jessie running on ec2
### Scenario:
[What you are trying to achieve and you can't?]
 I am trying  add resource for cron_d
```cron_d "backup_files" do
	minute "0"
	hour "23"
	user "root"
	command "/opt/backup.sh >> /var/log/backup.log 2>&1"
end```
### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
  Try to apply the resource.

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
 The resource is created.

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

        ```   Error executing action `create` on resource 'cron_d[backup_files]'
           ================================================================================

           NoMethodError
           -------------
           No resource or method named `create_template' for `LWRP resource cron_d from cookbook cron action provider "backup_files"'

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/cron/resources/d.rb:43:in `block in class_from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/recipes/backup.rb

            75: cron_d "backup_files" do
            76: 	minute "0"
            77: 	hour "23"
            78: 	user "root"
            79: 	command "/opt/backup.sh >> /var/log/backup.log 2>&1"
            80:
            81: end
            82:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/recipes/backup.rb:75:in `from_file'

           cron_d("backup_files") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :cron_d
             cookbook_name 
             recipe_name "backup"
             minute "0"
             hour "23"
             user "root"
             command "/opt/backup.sh >> /var/log/backup.log 2>&1"
           end```

**Comment by yvesjans** [comment]
+1 

We use the monitor_cloudwatch cookbook which uses the `create_template` resource. Looks like it got removed in https://github.com/chef-cookbooks/cron/pull/83

**Comment by tas50** [comment]
What versions of chef are you using because the template is still there in the action class and runs fine within testing.

**Comment by cthomaspdx** [comment]
@tas50 
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44

but on our builds we set 
chef-client (5.0.0)

**Comment by tas50** [comment]
@cthomaspdx chef-client 5.0 is the chef-client cookbook. What's the actual chef-client version on the nodes. You can run chef-client -v on a system to get that.

**Comment by cthomaspdx** [comment]
@tas50 Chef: 12.12.15

**Comment by nael-binary** [comment]
any solution?

**Comment by tas50** [comment]
Can you give this a try on the newest cookbook release? I made a few changes that might impact this

**Comment by cthomaspdx** [comment]
@tas50 Everything seems to be working form me on 4.1.1 Thanks!

**Comment by tas50** [comment]
Closing this out since it's fixed in the latest
